language: node_js
dist: trusty
sudo: false
node_js:
  - 4
  - 6
  - stable
before_install:
  - if [[ `npm -v` == 2*  ]]; then npm install -g npm@3; fi
  - npm install -g codecov
install:
  - npm install react react-dom
  - npm install
script:
  - npm run lint
  - npm test
after_success:
  - codecov
notifications:
  email: false
